import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<link
				rel='icon'
				href='/icon?<generated>'
				type='image/<generated>'
				sizes='<generated>'
			/>
			<link
				rel='apple-touch-icon'
				href='/apple-icon?<generated>'
				type='image/<generated>'
				sizes='<generated>'
			/>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
